# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307d7aa963a96be12461144e48e736ed271cf172d25b2100d2cdcce34c84256d5c5c42b1b89408cfad253fffd7bf9ae4993c4abd52d0c630d78ab06646e11196

test:
  secret_key_base: 0553f5919b76060494f8c30b9c22f5cb9aebe2ae76b2cdccc970d4e205622c7519933aed0c86e035abc37526b3eab713a4c588a3e397cbd09954c1ccca5482c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
