# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39efc3115b17c2bdcdf039b5a00349ee8acfe5c7c958d3aac6900ba6f9b7dedebc0c7677e6ef63f1775cf25924bbe0b3649bf3dc16c80bd6daddb6fe0b4ee85

test:
  secret_key_base: 5cd27a88ee347b011d94d37159d7597c1ea0f79d54c8b60d9edbdf1a7b31173d9bfcc8c88c5a305427b6ba054b390e1b50044244f39a6972b7aedb76bca02f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
