# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94098a9a7fd21674fb6ff34aac4d37c2c301ff47de92a9d02a7a66f902242b58452dea59c9bf15c12f2c64396cc94f507bbe0c1e1f312f2ba0a7f7eb0ff37ceb

test:
  secret_key_base: d376f3c0ad0de16929d72e8f27f7bb52475e67ad10883f44f100e7bcf0cf29ba0218676650e0def982a10c90f169ae16966a2986e8a19b39d25154821425fa53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
